###
POST http://localhost:4000/api/register/
content-type: application/json

{
  "email":"me7@me.com",
  "name": "Me",
  "password": "password123"
}

###
POST http://localhost:4000/api/login/
content-type: application/json

{
    "email": "me3@me.com",
    "password": "password2"
}

###
GET http://localhost:4000/api/user
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0Ijo0LCJlbWFpbCI6Im1lNkBtZS5jb20iLCJpYXQiOjE1ODA1NDY4MzAsImV4cCI6MTU4MDYzMzIzMH0.L90__sjoaNdLD9Zj4TZVvUG2oRwaZ-tqK2TZP71oWkY

###
GET http://localhost:4000/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0Ijo0LCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA0NTY0MzYsImV4cCI6MTU4MDU0MjgzNn0.vQ3JsI2_il0LvwkA-Mo6-7TEKolzEbK6_FJ5Lvq6GTI

###
GET http://localhost:4000/api/regions
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA1NDQyOTgsImV4cCI6MTU4MDYzMDY5OH0.gF_hgq1n1MEtz7SW0JOkYBRmfSRnr7Tar8QraRqNkmE
###
GET http://localhost:4000/api/regions/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA1NDQyOTgsImV4cCI6MTU4MDYzMDY5OH0.gF_hgq1n1MEtz7SW0JOkYBRmfSRnr7Tar8QraRqNkmE

###
GET http://localhost:4000/api/exercises
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA1NDQyOTgsImV4cCI6MTU4MDYzMDY5OH0.gF_hgq1n1MEtz7SW0JOkYBRmfSRnr7Tar8QraRqNkmE
###
GET http://localhost:4000/api/exercises/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA1NDQyOTgsImV4cCI6MTU4MDYzMDY5OH0.gF_hgq1n1MEtz7SW0JOkYBRmfSRnr7Tar8QraRqNkmE

###
POST https://localhost:4000/api/exercises/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA1NDcwNDYsImV4cCI6MTU4MDYzMzQ0Nn0.mWP5uW6ELnG3SBKlWW0tXsMtuDpqbgFDvQiX-vgvsTE
{
  "user_id": 1,
  "region_id": 4,
  "name": "Deadlift",
  "timestamp": 1580533729
}