###
POST http://localhost:4000/api/register/
content-type: application/json

{
  "email":"me7@me.com",
  "name": "Me",
  "password": "password123"
}

###
POST http://localhost:4000/api/login/
content-type: application/json

{
    "email": "me2@me.com",
    "password": "password1"
}

###
GET http://localhost:4000/api/user
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

###
GET http://localhost:4000/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

###
GET http://localhost:4000/api/regions
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o
###
GET http://localhost:4000/api/regions/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

###
GET http://localhost:4000/api/exercises
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o
###
GET http://localhost:4000/api/exercises/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

###
POST http://localhost:4000/api/exercises/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

{
  "region_id": 4,
  "name": "Deadlift",
  "timestamp": 1580533729
}
###
PUT http://localhost:4000/api/exercises/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzc1MjcsImV4cCI6MTU4MTI2MzkyN30.pCuuWdiMjyIUTKt5gdfmRKTWk_gv2MxvJLz1XrwQh3o

{
  "region_id": 4,
  "name": "Alivelift",
  "timestamp": 1580533729
}

###
GET http://localhost:4000/api/exercises/1/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODA4MzU4OTAsImV4cCI6MTU4MDkyMjI5MH0.eyHqbQxN9eoqd2DZzxjGKGiTaAipkwVMlXFqkZD_ee4
###
GET http://localhost:4000/api/exercises/1/sets/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODA4MzU4OTAsImV4cCI6MTU4MDkyMjI5MH0.eyHqbQxN9eoqd2DZzxjGKGiTaAipkwVMlXFqkZD_ee4

###
POST http://localhost:4000/api/exercises/1/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODA4MzU4OTAsImV4cCI6MTU4MDkyMjI5MH0.eyHqbQxN9eoqd2DZzxjGKGiTaAipkwVMlXFqkZD_ee4

{
  "exercise_id": 1,
  "reps": 4,
  "weight": "125"
}

###
PUT http://localhost:4000/api/exercises/1/sets/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lM0BtZS5jb20iLCJpYXQiOjE1ODA4NzQ0NDEsImV4cCI6MTU4MDk2MDg0MX0.hzfUuZebKjUFow-RITzhWoqbxPFrbfalIAg2XWZQOrM

{
  "reps": 4,
  "weight": "125"
}