###
POST https://bw-weightlifting-journal.herokuapp.com/api/register/
content-type: application/json

{
  "email":"me12@me.com",
  "name": "Me",
  "password": "password2",
  "admin":"false"
}

###
POST https://bw-weightlifting-journal.herokuapp.com/api/login/
content-type: application/json

{
    "email": "me@me.com",
    "password": "password"
}

###
GET https://bw-weightlifting-journal.herokuapp.com/api/user
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

###
GET https://bw-weightlifting-journal.herokuapp.com/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

###
GET https://bw-weightlifting-journal.herokuapp.com/api/regions
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE
###
GET https://bw-weightlifting-journal.herokuapp.com/api/regions/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE
###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

###
POST https://bw-weightlifting-journal.herokuapp.com/api/exercises/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

{
  "user_id": 1,
  "region_id": 4,
  "name": "Deadlift",
  "timestamp": 1580533729
}

###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/9/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE
###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/9/sets/28
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

###
POST https://bw-weightlifting-journal.herokuapp.com/api/exercises/9/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

{
  "exercise_id": 1,
  "reps": 4,
  "weight": "125"
}

###
PUT https://bw-weightlifting-journal.herokuapp.com/api/exercises/9/sets/28
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE

{
  "reps": 4,
  "weight": "125"
}

###
DELETE https://bw-weightlifting-journal.herokuapp.com/api/exercises/1/sets/29
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6Im1lQG1lLmNvbSIsImlhdCI6MTU4MDk5MTM2OCwiZXhwIjoxNTgxMDc3NzY4fQ.EOOKUdmzaJ5KlXOJI8TmKlv6Czv49W5CFE7FBHG3pXE