###
POST http://localhost:4000/auth/register/
content-type: application/json

{
  "email":"me2@me.com",
  "name": "Me",
  "password": "password123"
}

###
POST http://localhost:4000/auth/login/
content-type: application/json

{
    "email": "me2@me.com",
    "password": "password123"
}

###
GET http://localhost:4000/api/user
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODA0NTU4NjcsImV4cCI6MTU4MDU0MjI2N30.qYriq37NntovalRdVWQgUjH0T275X8xg2GntADX888g

###
GET http://localhost:4000/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODA0NTU4NjcsImV4cCI6MTU4MDU0MjI2N30.qYriq37NntovalRdVWQgUjH0T275X8xg2GntADX888g