###
POST https://bw-weightlifting-journal.herokuapp.com/api/register/
content-type: application/json

{
  "email":"me2@me.com",
  "name": "Me",
  "password": "password1",
  "admin":"false"
}

###
POST https://bw-weightlifting-journal.herokuapp.com/api/login/
content-type: application/json

{
    "email": "me2@me.com",
    "password": "password1"
}

###
GET https://bw-weightlifting-journal.herokuapp.com/api/user
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

###
GET https://bw-weightlifting-journal.herokuapp.com/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

###
GET https://bw-weightlifting-journal.herokuapp.com/api/regions
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA
###
GET https://bw-weightlifting-journal.herokuapp.com/api/regions/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA
###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/14
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

###
POST https://bw-weightlifting-journal.herokuapp.com/api/exercises/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

{
  "region_id": 4,
  "name": "Deadlift",
  "timestamp": 1581125467421
}

###
PUT https://bw-weightlifting-journal.herokuapp.com/api/exercises/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

{
  "region_id": 4,
  "name": "Alivelift",
  "timestamp": 1580533729
}

###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/17/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA
###
GET https://bw-weightlifting-journal.herokuapp.com/api/exercises/14/sets/28
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

###
POST https://bw-weightlifting-journal.herokuapp.com/api/exercises/17/sets
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

{
  "reps": "4",
  "weight": "125"
}

###
PUT https://bw-weightlifting-journal.herokuapp.com/api/exercises/9/sets/28
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA

{
  "reps": 4,
  "weight": "125"
}

###
DELETE https://bw-weightlifting-journal.herokuapp.com/api/exercises/1/sets/29
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJlbWFpbCI6Im1lMkBtZS5jb20iLCJpYXQiOjE1ODExNzg0OTEsImV4cCI6MTU4MTI2NDg5MX0.LBPH3LZGFbfWKEmwuA25JxpglU7x_yOtuA7FCAhpIlA